[theme]
primaryColor="#b7e4f7"
backgroundColor="#abc8d2"
secondaryBackgroundColor="#d5ebf1"
textColor="#262730"
"""
primaryColor="#d6dcff"
backgroundColor="#d6dcff"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[theme]
primaryColor="#0cc9ff"
backgroundColor="#efebeb"
secondaryBackgroundColor="#799ca8"
textColor="#000000"
"""

